# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, nixpkgs, modulesPath, ... }:
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1c6a6142-1952-48ed-aedb-1b0a79e244e1";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f4965cbc-2527-4105-b51e-0b5d5e3ef17c".device = "/dev/disk/by-uuid/f4965cbc-2527-4105-b51e-0b5d5e3ef17c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1884-44FF";
      fsType = "vfat";
    };

  #swapDevices =
  #  [ { device = "/dev/disk/by-uuid/cc177c18-771e-4403-8743-59edf3b90b26"; }
  #  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp63s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
