return {
    "xiyaowong/transparent.nvim",
    lazy = false,
    config = function()
      require("transparent").setup{
        groups = { -- table: default groups
          'Normal',
          'NormalNC', 
          'Comment',
          'Constant',
          'Special',
          'Identifier',
          'Statement',
          'PreProc',
          'Type',
          'Underlined',
          'Todo',
          'String',
          'Function',
          'Conditional',
          'Repeat',
          'Operator',
          'Structure',
          'LineNr',
          'NonText',
          'SignColumn',
          'CursorLineNr',
          'EndOfBuffer',
      },
      extra_groups = {
          "NormalFloat", 
          'FoldColumn',
          'Folded',
          'VertSplit',
          'StatusLine',
          'StatusLineNC',
          'TabLineFill',
          'TabLineSel',
          'TabLine',
          'CursorLine',
          'CursorColumn',
          'St_EmptySpace2',
          'ColorColumn',
          'FloatShadow',
          'FloatShadowThrough',
          'Visual',
          'QuickFixLine',
          'Pmenu',
          'PmenuKind',
          'PmenuExtra',
          'PmenuSbar',
          'PmenuThumb',
          'Folded',
          'FoldColumn',
        }, -- table: additional groups that should be cleared
      exclude_groups = {}, -- table: groups you don't want to clear
    }
    end,  
}
